name: cpp-linter

on: pull_request

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Add a new step here to run CMake and generate the compilation database
      - name: Generate Compilation Database
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
          # You might need additional CMake options depending on your project

      - uses: cpp-linter/cpp-linter-action@v2.7.5
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: ''
          lines-changed-only: diff
          database: build
          thread-comments: update
          step-summary: true

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
