name: cpp-linter

on:
  pull_request:
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  cpp-linter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
          sudo apt-get update
          sudo apt-get -yq --no-install-suggests --no-install-recommends install gcc-7 g++-7 valgrind

      - name: Generate Compilation Database
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
        env:
          BUILD_TYPE: Release

      - uses: cpp-linter/cpp-linter-action@v2.7.5
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: ''
          lines-changed-only: ${{ github.event_name == 'workflow_dispatch' && 'false' || 'diff' }}
          files-changed-only: ${{ github.event_name == 'workflow_dispatch' && 'false' || 'true' }}
          database: build
          thread-comments: update

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
